"""
SQL Formatter Module
Professional SQL formatting with proper indentation and structure.
"""

import re
import logging
from typing import List, Dict
from datetime import datetime
import sqlparse

logger = logging.getLogger(__name__)


class SQLFormatter:
    def __init__(self, config: Dict):
        self.config = config
        self.fmt_config = config.get("formatter", {})
        self.keyword_case = self.fmt_config.get("keyword_case", "upper")
        self.indent_width = self.fmt_config.get("indent_width", 4)
        self.reindent = self.fmt_config.get("reindent", True)
        self.strip_comments = self.fmt_config.get("strip_comments", False)

    def format_query(self, query) -> str:
        try:
            formatted = sqlparse.format(
                query.raw_sql,
                reindent=self.reindent,
                keyword_case=self.keyword_case,
                identifier_case="lower",
                strip_comments=self.strip_comments,
                indent_width=self.indent_width,
                indent_tabs=False,
                use_space_around_operators=True,
            )
            return self._post_process(formatted)
        except Exception as e:
            logger.warning(f"Formatting error: {e}")
            return query.raw_sql

    def _post_process(self, sql: str) -> str:
        sql = sql.rstrip()
        if not sql.endswith(";"):
            sql += ";"
        sql = re.sub(r",(?!\s)", ", ", sql)
        sql = re.sub(r"\n{3,}", "\n\n", sql)
        return sql

    def format_all_queries(self, queries: List) -> Dict[str, List[str]]:
        categorized: Dict[str, List[str]] = {}
        for query in queries:
            category = self._get_category_name(query.query_type)
            formatted = self.format_query(query)
            formatted_with_meta = self._add_metadata_comment(query, formatted)
            categorized.setdefault(category, []).append(formatted_with_meta)
        return categorized

    def _get_category_name(self, query_type) -> str:
        from sql_parser.sql_parser import QueryType
        mapping = {
            QueryType.SELECT: "SELECT Queries",
            QueryType.WITH: "CTE Queries",
            QueryType.INSERT: "INSERT Queries",
            QueryType.UPDATE: "UPDATE Queries",
            QueryType.DELETE: "DELETE Queries",
            QueryType.MERGE: "MERGE Queries",
            QueryType.CREATE: "DDL - CREATE",
            QueryType.ALTER: "DDL - ALTER",
            QueryType.DROP: "DDL - DROP",
            QueryType.TRUNCATE: "DDL - TRUNCATE",
            QueryType.EXEC: "EXEC",
            QueryType.STORED_PROCEDURE: "STORED PROCEDURES",
            QueryType.VIEW: "VIEWS",
            QueryType.FUNCTION: "FUNCTIONS",
            QueryType.TRIGGER: "TRIGGERS",
            QueryType.INDEX: "INDEXES",
            QueryType.TRANSACTION: "TRANSACTION BLOCKS",
        }
        return mapping.get(query_type, "Uncategorized")

    def _add_metadata_comment(self, query, formatted_sql: str) -> str:
        meta = [
            f"-- Source File : {query.source_file}",
            f"-- Query Type  : {query.query_type.value}",
            f"-- Line Number : {query.line_number_start} - {query.line_number_end}",
            f"-- Complexity  : {query.complexity_score}",
            f"-- Risk Level  : {query.risk_level}",
            f"-- Importance  : {query.importance_score}",
        ]
        if query.table_names:
            meta.append(f"-- Tables      : {', '.join(query.table_names)}")
        sep = "-" * 80
        return f"\n{sep}\n" + "\n".join(meta) + f"\n{sep}\n{formatted_sql}\n"

    def generate_master_sql_document(self, queries: List, scan_metadata: Dict) -> str:
        sections = [self._generate_header(scan_metadata)]
        categorized = self.format_all_queries(queries)
        order = [
            "DDL - CREATE", "DDL - ALTER", "DDL - DROP", "DDL - TRUNCATE",
            "VIEWS", "FUNCTIONS", "STORED PROCEDURES", "EXEC", "TRIGGERS",
            "INDEXES", "SELECT Queries", "CTE Queries", "INSERT Queries",
            "UPDATE Queries", "DELETE Queries", "MERGE Queries",
            "TRANSACTION BLOCKS", "Uncategorized",
        ]
        for section_name in order:
            if section_name in categorized:
                sections.append(self._generate_section(section_name, categorized[section_name]))
        for cat, qlist in categorized.items():
            if cat not in order:
                sections.append(self._generate_section(cat, qlist))
        sections.append(self._generate_footer())
        return "\n\n".join(sections)

    def _generate_header(self, metadata: Dict) -> str:
        lines = [
            "/*", "=" * 76,
            "  SQL QUERY CONSOLIDATION MASTER DOCUMENT",
            "  Generated by SQL Consolidator Tool v1.0",
            "=" * 76, "",
            f"  Generated On      : {metadata.get('scan_datetime', datetime.now().strftime('%Y-%m-%d %H:%M:%S'))}",
            f"  Input Directory   : {metadata.get('input_directory', 'N/A')}",
            f"  Files Scanned     : {metadata.get('total_files_scanned', 0)}",
            f"  Queries Found     : {metadata.get('total_queries_found', 0)}",
            f"  Unique Queries    : {metadata.get('total_unique_queries', 0)}",
            f"  Duplicates Removed: {metadata.get('total_duplicates_removed', 0)}",
            "", "  QUERY DISTRIBUTION:",
        ]
        for qtype, count in metadata.get("query_type_distribution", {}).items():
            lines.append(f"    {qtype:<30} : {count}")
        lines += ["", "=" * 76, "*/", ""]
        return "\n".join(lines)

    def _generate_section(self, name: str, queries: List[str]) -> str:
        header = "\n".join([
            "", "/" + "=" * 79,
            f"||  {name.upper():<74} ||",
            f"||  Total: {len(queries):<70} ||",
            "=" * 79 + "/",
        ])
        return header + "\n" + "\nGO\n".join(queries)

    def _generate_footer(self) -> str:
        return "\n".join([
            "", "/*", "=" * 76,
            "  END OF MASTER SQL DOCUMENT",
            f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "=" * 76, "*/",
        ])
